const $=id=>document.getElementById(id),KEY='emaus_expenses_v2';let expenses=JSON.parse(localStorage.getItem(KEY)||'[]');
const money=n=>new Intl.NumberFormat('es-MX',{style:'currency',currency:'MXN'}).format(n||0),today=localDate(new Date());$('date').value=today;
const esc=(v='')=>String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));function localDate(d){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function monthRange(offset=0){const n=new Date(),d=new Date(n.getFullYear(),n.getMonth()+offset,1),e=new Date(d.getFullYear(),d.getMonth()+1,0);return[localDate(d),localDate(e)]}
function filtered(){const f=$('from').value,t=$('to').value,q=($('search')?.value||'').toLowerCase();return expenses.filter(x=>(!f||x.date>=f)&&(!t||x.date<=t)&&(!q||`${x.concept} ${x.recipient} ${x.note||''} ${x.observations||''}`.toLowerCase().includes(q))).sort((a,b)=>b.date.localeCompare(a.date));}
function item(x){return `<article class="item"><div><h3>${esc(x.concept)}</h3><div class="meta">${esc(x.date)} · Recibe: ${esc(x.recipient)}</div>${x.note?`<div class="note">Nota/recibo: ${esc(x.note)}</div>`:''}${x.observations?`<div class="note">${esc(x.observations)}</div>`:''}${x.receiptName?`<div class="attachment">📎 ${esc(x.receiptName)}</div>`:''}<button class="delete" onclick="removeExpense('${x.id}')">Eliminar</button></div><div class="money">${money(x.amount)}</div></article>`}
function render(){const data=filtered(),recent=[...expenses].sort((a,b)=>b.date.localeCompare(a.date)).slice(0,5);$('reportTotal').textContent=money(data.reduce((s,x)=>s+Number(x.amount),0));$('empty').style.display=data.length?'none':'block';$('list').innerHTML=data.map(item).join('');$('recentEmpty').style.display=recent.length?'none':'block';$('recentList').innerHTML=recent.map(item).join('');const[a,b]=monthRange();$('total').textContent=money(expenses.filter(x=>x.date>=a&&x.date<=b).reduce((s,x)=>s+Number(x.amount),0));}
function save(){localStorage.setItem(KEY,JSON.stringify(expenses))}function go(id){document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id===id));document.querySelectorAll('.bottom button').forEach(b=>b.classList.toggle('active',b.dataset.go===id));scrollTo(0,0)}document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go));
$('expenseForm').onsubmit=e=>{e.preventDefault();const file=$('receipt').files[0];expenses.push({id:crypto.randomUUID?.()||Date.now().toString(),date:$('date').value,amount:Number($('amount').value),concept:$('concept').value.trim(),recipient:$('recipient').value.trim(),note:$('note').value.trim(),observations:$('observations').value.trim(),receiptName:file?.name||'',receiptType:file?.type||''});save();e.target.reset();$('date').value=today;render();go('home');alert('Gasto guardado correctamente.')};
window.removeExpense=id=>{if(confirm('¿Eliminar este gasto?')){expenses=expenses.filter(x=>x.id!==id);save();render()}};$('search').oninput=render;$('from').onchange=render;$('to').onchange=render;
document.querySelectorAll('[data-range]').forEach(b=>b.onclick=()=>{let r;if(b.dataset.range==='month')r=monthRange();if(b.dataset.range==='previous')r=monthRange(-1);if(b.dataset.range==='year'){const y=new Date().getFullYear();r=[`${y}-01-01`,`${y}-12-31`]}[$('from').value,$('to').value]=r;render()});
$('exportBtn').onclick=()=>{const data=filtered();if(!data.length)return alert('No hay gastos en el período seleccionado.');if(typeof XLSX==='undefined')return alert('No se pudo cargar el módulo de Excel. Revisa tu conexión e intenta nuevamente.');const total=data.reduce((s,x)=>s+Number(x.amount),0),rows=[['IGLESIA EMAÚS – CONTROL DE GASTOS'],[`Período: ${$('from').value||'inicio'} a ${$('to').value||today}`],[`Total gastos: ${money(total)}`],[],['Fecha','Gasto','Concepto / Actividad','Quién recibe','Nota / Recibo','Observaciones','Comprobante'],...data.map(x=>[x.date,Number(x.amount),x.concept,x.recipient,x.note||'',x.observations||'',x.receiptName||'']),['TOTAL',total,'','','','','']];const ws=XLSX.utils.aoa_to_sheet(rows);ws['!cols']=[{wch:14},{wch:16},{wch:32},{wch:25},{wch:30},{wch:35},{wch:28}];const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,'Gastos');XLSX.writeFile(wb,`gastos-emaus-${$('from').value||'inicio'}-${$('to').value||today}.xlsx`)};
$('backupBtn').onclick=()=>{const blob=new Blob([JSON.stringify({app:'Iglesia Emaús - Control de Gastos',version:1,created:today,expenses},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`respaldo-emaus-${today}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)};
$('restoreInput').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{const data=JSON.parse(await file.text()),list=Array.isArray(data)?data:data.expenses;if(!Array.isArray(list))throw 0;if(!confirm(`Se restaurarán ${list.length} registros y se reemplazarán los actuales. ¿Continuar?`))return;expenses=list;save();render();alert('Respaldo restaurado correctamente.')}catch{alert('El archivo de respaldo no es válido.')}finally{e.target.value=''}};
const initial=monthRange();$('from').value=initial[0];$('to').value=initial[1];render();